version: '2'

run:
  tests: true
  build-tags:
    - bench
    - !bench

linters-settings:
  funlen:
    lines: 150
    statements: 80
  depguard:
    rules:
      Main:
        files:
          - $all
          - '!$test'
        allow:
          - $gostd
          - github.com/stretchr/testify
          - github.com/stretchr/testify/require
          - github.com/M-kos/anti_brutforce/internal/services/whitelist-service
          - github.com/M-kos/anti_brutforce/internal/services/blacklist-service
          - github.com/M-kos/anti_brutforce/internal/api
          - github.com/M-kos/anti_brutforce/internal/api/pb
          - github.com/M-kos/anti_brutforce/internal/config
          - github.com/M-kos/anti_brutforce/internal/models
          - github.com/M-kos/anti_brutforce/internal/services/limitter-cli-service
          - github.com/redis
      Test:
        files:
          - $test
        allow:
          - $gostd
          - github.com/stretchr/testify
          - github.com/stretchr/testify/require
          - github.com/M-kos/anti_brutforce/internal/services/whitelist-service
          - github.com/M-kos/anti_brutforce/internal/services/blacklist-service
          - github.com/M-kos/anti_brutforce/internal/api
          - github.com/M-kos/anti_brutforce/internal/api/pb
          - github.com/M-kos/anti_brutforce/internal/config
          - github.com/M-kos/anti_brutforce/internal/models
          - github.com/M-kos/anti_brutforce/internal/services/limitter-cli-service
          - github.com/redis
  tagliatelle:
    case:
      rules:
        json: snake

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - dupl
        - gocyclo
        - gosec

linters:
  enable:
    - asciicheck
    - dogsled
    - dupl
    - bodyclose
    - durationcheck
    - errorlint
    - exhaustive
    - copyloopvar
    - funlen
    - gci
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - gofumpt
    - goheader
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - importas
    - ineffassign
    - lll
    - makezero
    - misspell
    - nestif
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - stylecheck
    - tagliatelle
    - thelper
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
