name: Anti Bruteforce

on:
  push:
    branches:
      - feature*
      - fix*

env:
  GO111MODULE: "on"

jobs:
  lint:
    name: Run Lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ~1.23

      - name: Check out code
        uses: actions/checkout@v3

      - name: Linters
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.63.4

  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.23

      - name: Check out code
        uses: actions/checkout@v3

      - name: Unit tests
        run: go test -v -count=1 -race -timeout=1m ./...

      - name: Optimization tests
        run: go test -v -count=1 -timeout=1m -tags bench ./...

  tests_by_makefile:
    name: Run Tests by Makefile
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.23

      - name: Check out code
        uses: actions/checkout@v3

      - name: make lint
        run: make lint

      - name: make build
        run: make build

      - name: make test
        run: make test
